on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
name: update_xfl_epa

jobs:
  update:
    name: Update Combine Data
    runs-on: ${{ matrix.config.os }}

    build:
      fail-fast: false
      runs-on: ubuntu-latest
        matrix:
          r-verson: ["3.3"]
    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          
      - name: Update XFL PBP
        run: Rscript -e 'source("pbp.r")'

      - name: Commit and push updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "XFL EPA PBP Update `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
