on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  #pull_request:
  #  branches: [ main ]
  #
name: update_xfl_epa

jobs:
  update:
    name: rebuild_pbp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/fastrmodels
            ropensci/piggyback

      - name: Update XFL PBP
        run: Rscript -e 'source("pbp.r")'

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update XFL PBP" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
