on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
name: update_xfl_epa

jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
     
      - name: Run ngs update script
        run: Rscript -e 'source("pbp.r")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "XFL PBP UPDATE `date`" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
